# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4712ea3bbba15d5e307793049b1f097050bc11eea90415ad91cc78cd003b9319cb2d479b615b67c83b0f6752c69c956df1b639d551e73111c50996990deba07

test:
  secret_key_base: 3e0335adb08206b3827f567e8a6e65d07e886a17899d6e5c82b2a664eb2c33acc1e4dbf11c0a1dd764627d35af5703a0eeff6733c1a8c3d96b1ca0c5bb3e0694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
